### ISSUE TITLE
(accfg) Setup-Await Overlap

### ISSUE THREAD

**Issue by AntonLydike** [KULeuven-MICAS/snax-mlir#141]
This requires us:
- [x] Block level deduplication #139 
- [ ] basic `scf.for` deduplication #140 
- [ ] advanced `scf.for` deduplication (handling computations on the loop variable) #140 
- [ ] Moving `await`s out of `scf.if` blocks?

**Comment by JosseVanDelm** [comment]
@AntonLydike we can close this, right?
