### ISSUE TITLE
Tracking issue: Move to generic runtime

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snax-mlir#48]
Since KULeuven-MICAS/snitch_cluster#57 we have a generic LLVM support to move to LLVM main.

This would allow us to:
* Remove opaque pointer support (and ditch `mlir-translate-16`)
* Use properties in MLIR (and ditch `tomlir16.py` and `tomlir18.py`)
* Have access to new bytecode support (needed for TOSA import from tensorflow)

To complete this issue, I need to:
- [x] Update the version in the container of KULeuven-MICAS/snitch_cluster to use the version with the generic runtime
  - [x] Adapt sha's and commit hashes
  - [x] Install llvm
  - [x] Add rtl-generic paths
- [x] Change the rules of compilation in `runtime/Makefile.rules` to:
  - [x] Use the generic riscv target
  - [x] Not use tomlir-16/18.py anymore
  - [x] Use a different version of LLVM
- [ ] Update readme to reflect newest flow
